//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf2Praktika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_Artur_ShabunovEntities : DbContext
    {
        public db_Artur_ShabunovEntities()
            : base("name=db_Artur_ShabunovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tGroup> tGroups { get; set; }
        public virtual DbSet<tStudent> tStudents { get; set; }
        public virtual DbSet<tTeacher> tTeachers { get; set; }
    }
}
