//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf2Praktika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_Artur_ShabunovEntitiesInput : DbContext
    {
        public db_Artur_ShabunovEntitiesInput()
            : base("name=db_Artur_ShabunovEntitiesInput")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tGroup> tGroups { get; set; }
        public virtual DbSet<tStudent> tStudents { get; set; }
        public virtual DbSet<tTeacher> tTeachers { get; set; }
    }
}
