//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf2Praktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStudent
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int IDCode { get; set; }
        public string School { get; set; }
        public int Class { get; set; }
        public string ContactEmail { get; set; }
        public string Telephone { get; set; }
        public int GroupFK { get; set; }
    
        public virtual tGroup tGroup { get; set; }
    }
}
